name: "Update"

concurrency:
  group: update

on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore
    - docs/*
  workflow_dispatch:

jobs:
  build:
    name: Update
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout 📋
      uses: actions/checkout@v2

    - name: Setup 🏗️
      run: |
        sudo apt-get install --yes xml2rfc ruby
        sudo gem install kramdown-rfc

    - name: Generate 🔨
      run: |
        /usr/local/bin/kramdown-rfc2629 --v3 draft-chariton-ipcaa.mkd > docs/draft.xml
        cd docs
        xml2rfc --text --html --v3 draft.xml
        mv draft.html index.html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
